config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/resume', to: 'pages#resume'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def resume
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sarah Katherine Francis | Full-Stack Developer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/png" href="<%= asset_path('favicon.png') %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  </head>
  <body>
    <% unless current_page?(root_path) %>
      <div class="sidebar">
        <%= render 'shared/sidebar' %>
      </div>
      <div class="content">
        <%= yield %>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/pages/_about.html.erb
<section id="about">
  <h3 class="page-title white-text raspberry">ABOUT</h3>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-4">
        <%= image_tag "profile.jpg", :class => "profile" %>
      </div>
      <div class="col-md-8 col-sm-12 paragraph-container">
        <h2>About me</h2>
        <p>
          As a Full Stack Developer, I bring a unique combination of skills and
          experience to my work. Before pursuing web development, I worked as a
          kindergarten teacher for several years. After discovering my passion for
          technology, I decided to enroll in the Le Wagon Web Development
          bootcamp and have since continued to hone my skills and stay up-to-date
          with the latest technologies.
        </p>
        <p>
          I have always sought out opportunities and challenges that are
          meaningful to me, and my passion for helping others and solving problems
          has remained a constant throughout my professional journey. As a web
          developer, I leverage my meticulous attention to detail, my love for
          creating things, and my unwavering work ethic to make a positive impact
          on the world.
        </p>
        <p>
          Current focus: <strong>Ruby on Rails</strong> //<strong>React</strong>
          //<strong>Responsive Design</strong>
        </p>
      </div>
    </div>
  </div>
</section>

app/views/pages/_blog.html.erb
<section id="blog">
  <h2 class="page-title white-text raspberry">BLOG</h2>
  <div class="container">
    <p>Stay tuned for the latest updates and insights.</p>
  </div>
</section>

app/views/pages/_contact.html.erb
<section id="contact">
  <h3 class="page-title white-text raspberry">CONTACT</h3>
  <div class="container">
    <p class="contact-details">
      <button><a href="mailto:sarah.katherinefrancis@gmail.com"><i class="fa-solid fa-envelope contact-icon"></i></a></button>
      <a href="mailto:sarah.katherinefrancis@gmail.com">sarah.katherinefrancis@gmail.com</a>
    </p>
    <p class="contact-details">
      <button><a href="https://github.com/SarahKatherineFrancis"><i class="fa-brands fa-github contact-icon"></i></a></button>
      <a href="https://github.com/SarahKatherineFrancis">github.com/SarahKatherineFrancis</a>
    </p>
    <p class="contact-details">
      <button><a href="https://www.linkedin.com/in/sarah-kfrancis"><i class="fa-brands fa-linkedin contact-icon"></i></a></button>
      <a href="https://www.linkedin.com/in/sarah-kfrancis">linkedin.com/in/sarah-kfrancis</a>
    </p>
  </div>
</section>

app/views/pages/_education.html.erb
<section id="education">
  <h3 class="page-title white-text raspberry">EDUCATION</h3>
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="education-card">
          <div class="card-content">
            <a href="http://www.sun.ac.za/english" class="card-title">
              STELLENBOSCH UNIVERSITY
            </a>
            <p>Stellenbosch, South Africa</p>
            <ul>
              <li>B.A. in Humanities</li>
              <li>Major in Psychology, Sociology & MetaScience</li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="education-card">
          <div class="card-content">
            <a href="https://www.lewagon.com/" class="card-title">
              LE WAGON
            </a>
            <p>Cape Town, South Africa</p>
            <ul>
              <li>Web Development</li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="education-card">
          <div class="card-content">
            <a href="https://www.shecodes.io/" class="card-title">
              SHECODES
            </a>
            <p>Online</p>
            <ul>
              <li>SheCodes Basics</li>
              <li>SheCodes Plus</li>
              <li>SheCodes Responsive</li>
              <li>SheCodes React</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/_projects.html.erb
<section id="projects">
  <h3 class="page-title white-text raspberry">PROJECTS</h3>
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-6 col-sm-12 mb-5">
        <div class="project-card medium">
          <div class="card-image">
            <%= image_tag "journo.png", :class => "image"%>
          </div>
          <div class="card-content">
            <span class="card-title">
              Journo
            </span>
            <p>
              An app that provides personalized activity recommendations for
              travelers and includes a journal feature to capture and store
              their trip experiences.
            </p>
          </div>
          <div class="card-flip">
            <span class="card-title">
              Accomplishments
            </span>
            <ul>
              <li><strong>Ruby on Rails</strong> backend</li>
              <li>User authentication via <strong>Devise</strong></li>
              <li>Integrated <strong>OpenAI API</strong></li>
              <li>Integrated <strong>Mapbox API</strong></li>
            </ul>
            <hr>
            <div class="card-action">
              <a href="https://www.travel-journo.me">
                <i class="fa-solid fa-globe"></i>
              </a>
              <a href="https://github.com/SarahKatherineFrancis/journo" aria-label="View Source">
                <i class="fa-brands fa-github"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-12 mb-5">
        <div class="project-card medium">
          <div class="card-image">
            <%= image_tag "furr.png", :class => "image"%>
          </div>
          <div class="card-content">
            <span class="card-title">
              Furr
            </span>
            <p>
              An app that connects pet owners with available pet sitters,
              making it easier for pet owners to find trusted care for their
              pets.
            </p>
          </div>
          <div class="card-flip">
            <span class="card-title">
              Accomplishments
            </span>
            <ul>
              <li><strong>Ruby on Rails</strong> backend</li>
              <li>User authentication via <strong>Devise</strong></li>
              <li>Designed in <strong>Bootstrap</strong></li>
              <li>Integrated <strong>Mapbox API</strong></li>
            </ul>
            <hr>
            <div class="card-action">
              <a href="http://furr.herokuapp.com/">
                <i class="fa-solid fa-globe"></i>
              </a>
              <a href="https://github.com/SarahKatherineFrancis/furr">
                <i class="fa-brands fa-github"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-12 mb-5">
        <div class="project-card medium">
          <div class="card-image">
            <%= image_tag "lumo.png", :class => "image"%>
          </div>
          <div class="card-content">
            <span class="card-title">
              Lumo
            </span>
            <p>
              A dictionary app that is useful for anyone looking to quickly
              find the definition of a word or expand their vocabulary.
            </p>
          </div>
          <div class="card-flip">
            <span class="card-title">
              Accomplishments
            </span>
            <ul>
              <li>Implemented <strong>React</strong></li>
              <li>Integrated <strong>SheCodes Dictionary API</strong></li>
              <li>Designed in <strong>Bootstrap</strong></li>
              <li>Fully <strong>responsive</strong> designs</li>
            </ul>
            <hr>
            <div class="card-action">
              <a href="https://angry-booth-422a13.netlify.app/">
                <i class="fa-solid fa-globe"></i>
              </a>
              <a href="https://github.com/SarahKatherineFrancis/react-dictionary-app" aria-label="View Source">
                <i class="fa-brands fa-github"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-12 mb-5">
        <div class="project-card medium">
          <div class="card-image">
            <%= image_tag "weather.png", :class => "image"%>
          </div>
          <div class="card-content">
            <span class="card-title">
              SkyCast
            </span>
            <p>
              A weather app that provides users with up-to-date information
              about current and future weather conditions for a specific
              location.
            </p>
          </div>
          <div class="card-flip">
            <span class="card-title">
              Accomplishments
            </span>
            <ul>
              <li>Implemented <strong>React</strong></li>
              <li>Integrated <strong>OpenWeather API</strong></li>
              <li>Designed in <strong>Bootstrap</strong></li>
              <li>Fully <strong>responsive</strong> designs</li>
            </ul>
            <hr>
            <div class="card-action">
              <a href="https://unruffled-agnesi-0b02b9.netlify.app/">
                <i class="fa-solid fa-globe"></i>
              </a>
              <a href="https://github.com/SarahKatherineFrancis/react-weather-app" aria-label="View Source">
                <i class="fa-brands fa-github"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/_skills.html.erb
<section id="skills">
  <h3 class="page-title white-text raspberry">SKILLS</h3>
  <div class="container">
    <div class="card mb-5">
      <div class="class-content">
        <h4>Front-End</h4>
        <hr>
        <div class="row text-center">
          <div class="col-2">
            <div class="skill-item">
              <i class="fa-brands fa-html5" style="color:#E44D27"></i>
              <span>HTML5</span>
            </div>
          </div>
          <div class="col-2">
            <div class="skill-item">
              <i class="fa-brands fa-css3-alt" style="color:#3A9ADB"></i>
              <span>CSS3</span>
            </div>
          </div>
          <div class="col-2">
            <div class="skill-item">
              <i class="fa-brands fa-square-js" style="color:#D5BA32"></i>
              <span>JavaScript</span>
            </div>
          </div>
          <div class="col-2">
            <div class="skill-item">
              <i class="fa-brands fa-react" style="color:#63D8FA"></i>
              <span>React</span>
            </div>
          </div>
          <div class="col-2">
            <div class="skill-item">
              <i class="fa-brands fa-sass" style="color:#CD679A"></i>
              <span>SASS</span>
            </div>
          </div>
          <div class="col-2">
            <div class="skill-item">
              <i class="fa-brands fa-bootstrap" style="color:#26103A"></i>
              <span>Bootstrap</span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="class-content">
        <h4>Back-End</h4>
        <hr>
        <div class="row text-center">
          <div class="col-2">
            <div class="skill-item">
              <%= image_tag "ruby.png", :class => "skill-icon" %>
              <span>Ruby</span>
            </div>
          </div>
          <div class="col-2">
            <div class="skill-item">
              <%= image_tag "rails.png", :class => "skill-icon" %>
              <span>Rails</span>
            </div>
          </div>
          <div class="col-2">
            <div class="skill-item">
              <%= image_tag "postgresql.png", :class => "skill-icon" %>
              <span>PostgreSQL</span>
            </div>
          </div>
          <div class="col-2">
            <div class="skill-item">
              <%= image_tag "api.png", :class => "skill-icon" %>
              <span>RESTful APIs</span>
            </div>
          </div>
          <div class="col-2">
            <div class="skill-item">
              <%= image_tag "heroku.png", :class => "skill-icon"%>
              <span>Heroku</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/about.html.erb
<section id="about">
  <h3 class="page-title white-text raspberry">ABOUT</h3>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-4">
        <%= image_tag "profile.jpg", :class => "profile" %>
      </div>
      <div class="col-md-8 paragraph-container">
        <h2>Who am I?</h2>
        <p>
          As a Full Stack Developer, I bring a unique combination of skills and
          experience to my work. Before pursuing web development, I worked as a
          kindergarten teacher for several years. After discovering my passion for
          technology, I decided to enroll in the Le Wagon Web Development
          bootcamp and have since continued to hone my skills and stay up-to-date
          with the latest technologies.
        </p>
        <p>
          I have always sought out opportunities and challenges that are
          meaningful to me, and my passion for helping others and solving problems
          has remained a constant throughout my professional journey. As a web
          developer, I leverage my meticulous attention to detail, my love for
          creating things, and my unwavering work ethic to make a positive impact
          on the world.
        </p>
        <p>
          Current focus: <strong>Ruby on Rails</strong> //<strong>React</strong>
          //<strong>Responsive Design</strong>
        </p>
      </div>
    </div>
  </div>
</section>

app/views/pages/contact.html.erb
<section id="contact">
  <h3 class="page-title white-text raspberry">CONTACT</h3>
  <div class="container">
    <p class="contact-details">
      <button><a href="mailto:sarah.katherinefrancis@gmail.com"><i class="fa-solid fa-envelope contact-icon"></i></a></button>
      <a href="mailto:sarah.katherinefrancis@gmail.com">sarah.katherinefrancis@gmail.com</a>
    </p>
    <p class="contact-details">
      <button><a href="https://github.com/SarahKatherineFrancis"><i class="fa-brands fa-github contact-icon"></i></a></button>
      <a href="https://github.com/SarahKatherineFrancis">github.com/SarahKatherineFrancis</a>
    </p>
    <p class="contact-details">
      <button><a href="https://www.linkedin.com/in/sarah-kfrancis"><i class="fa-brands fa-linkedin contact-icon"></i></a></button>
      <a href="https://www.linkedin.com/in/sarah-kfrancis">linkedin.com/in/sarah-kfrancis</a>
    </p>
  </div>
</section>

app/views/pages/education.html.erb
<section id="education">
  <h3 class="page-title white-text raspberry">EDUCATION</h3>
  <div class="container">
    <div class="row">
      <div class="col-4">
        <div class="education-card">
          <div class="card-content">
            <p class="card-title">STELLENBOSCH UNIVERSITY</p>
            <p>Stellenbosch, South Africa</p>
            <ul>
              <li>B.A. in Humanities</li>
              <li>Major in Psychology, Sociology & MetaScience</li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-4">
        <div class="education-card">
          <div class="card-content">
            <p class="card-title">LE WAGON</p>
            <p>Cape Town, South Africa</p>
            <ul>
              <li>Web Development</li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-4">
        <div class="education-card">
          <div class="card-content">
            <p class="card-title">SHECODES</p>
            <p>Online</p>
            <ul>
              <li>SheCodes Basics</li>
              <li>SheCodes Plus</li>
              <li>SheCodes Responsive</li>
              <li>SheCodes React</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/home.html.erb
<div class="background flex">
  <div class="flex">
    <div class="text">
      Hello, I'm <span class="highlight">Sarah Francis</span>.
      <br>
      I'm a full-stack developer.
    </div>
    <%= link_to resume_path, class: "button" do %>
      <span>
        View my work
        <i class="fa-solid fa-arrow-right fa-fade highlight"></i>
      </span>
    <% end %>
  </div>
</section>

app/views/pages/projects.html.erb
<section class="projects">
  <h3 class="page-title white-text raspberry">PROJECTS</h3>
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-lg-6 col-sm-12 mb-5">
        <div class="project-card medium">
          <div class="card-image">
            <%= image_tag "journo.png", :class => "image"%>
          </div>
          <div class="card-content">
            <span class="card-title">
              Journo
            </span>
            <p>
              An app that provides personalized activity recommendations for
              travelers and includes a journal feature to capture and store
              their trip experiences.
            </p>
          </div>
          <div class="card-reveal">
            <span class="card-title">
              Accomplishments
            </span>
            <ul>
              <li><strong>Ruby on Rails</strong> backend</li>
              <li>User authentication via <strong>Devise</strong></li>
              <li>Integrated <strong>OpenAI API</strong></li>
              <li>Integrated <strong>Mapbox API</strong></li>
            </ul>
            <hr>
            <div class="card-action">
              <a href="https://www.travel-journo.me">
                <i class="fa-solid fa-globe"></i>
              </a>
              <a href="https://github.com/SarahKatherineFrancis/journo" aria-label="View Source">
                <i class="fa-brands fa-github"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-lg-6 col-sm-12 mb-5">
        <div class="project-card medium">
          <div class="card-image">
            <%= image_tag "furr.png", :class => "image"%>
          </div>
          <div class="card-content">
            <span class="card-title">
              Furr
            </span>
            <p>
              An app that connects pet owners with available pet sitters,
              making it easier for pet owners to find trusted care for their
              pets.
            </p>
          </div>
          <div class="card-reveal">
            <span class="card-title">
              Accomplishments
            </span>
            <ul>
              <li><strong>Ruby on Rails</strong> backend</li>
              <li>User authentication via <strong>Devise</strong></li>
              <li>Designed in <strong>Bootstrap</strong></li>
              <li>Integrated <strong>Mapbox API</strong></li>
            </ul>
            <hr>
            <div class="card-action">
              <a href="http://furr.herokuapp.com/">
                <i class="fa-solid fa-globe"></i>
              </a>
              <a href="https://github.com/SarahKatherineFrancis/furr">
                <i class="fa-brands fa-github"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-lg-6 col-sm-12 mb-5">
        <div class="project-card medium">
          <div class="card-image">
            <%= image_tag "lumo.png", :class => "image"%>
          </div>
          <div class="card-content">
            <span class="card-title">
              Lumo
            </span>
            <p>
              A dictionary app that is useful for anyone looking to quickly
              find the definition of a word or expand their vocabulary.
            </p>
          </div>
          <div class="card-reveal">
            <span class="card-title">
              Accomplishments
            </span>
            <ul>
              <li>Implemented <strong>React</strong></li>
              <li>Integrated <strong>SheCodes Dictionary API</strong></li>
              <li>Designed in <strong>Bootstrap</strong></li>
              <li>Fully <strong>responsive</strong> designs</li>
            </ul>
            <hr>
            <div class="card-action">
              <a href="https://angry-booth-422a13.netlify.app/">
                <i class="fa-solid fa-globe"></i>
              </a>
              <a href="https://github.com/SarahKatherineFrancis/react-dictionary-app" aria-label="View Source">
                <i class="fa-brands fa-github"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-lg-6 col-sm-12 mb-5">
        <div class="project-card medium">
          <div class="card-image">
            <%= image_tag "weather.png", :class => "image"%>
          </div>
          <div class="card-content">
            <span class="card-title">
              SkyCast
            </span>
            <p>
              A weather app that provides users with up-to-date information
              about current and future weather conditions for a specific
              location.
            </p>
          </div>
          <div class="card-reveal">
            <span class="card-title">
              Accomplishments
            </span>
            <ul>
              <li>Implemented <strong>React</strong></li>
              <li>Integrated <strong>OpenWeather API</strong></li>
              <li>Designed in <strong>Bootstrap</strong></li>
              <li>Fully <strong>responsive</strong> designs</li>
            </ul>
            <hr>
            <div class="card-action">
              <a href="https://unruffled-agnesi-0b02b9.netlify.app/">
                <i class="fa-solid fa-globe"></i>
              </a>
              <a href="https://github.com/SarahKatherineFrancis/react-weather-app" aria-label="View Source">
                <i class="fa-brands fa-github"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/resume.html.erb
<%= render 'about' %>
<%= render 'projects' %>
<%= render 'skills' %>
<%= render 'education' %>
<%= render 'contact' %>
<%= render 'blog' %>

app/views/pages/skills.html.erb
<section class="skills">
  <h3 class="page-title white-text raspberry">SKILLS</h3>
  <div class="container">
    <div class="card mb-5">
      <div class="class-content">
        <h4>Front-End</h4>
        <hr>
        <div class="row text-center">
          <div class="col-2">
            <div class="skill-item">
              <i class="fa-brands fa-html5" style="color:#E44D27"></i>
              <span>HTML5</span>
            </div>
          </div>
          <div class="col-2">
            <div class="skill-item">
              <i class="fa-brands fa-css3-alt" style="color:#3A9ADB"></i>
              <span>CSS3</span>
            </div>
          </div>
          <div class="col-2">
            <div class="skill-item">
              <i class="fa-brands fa-square-js" style="color:#D5BA32"></i>
              <span>JavaScript</span>
            </div>
          </div>
          <div class="col-2">
            <div class="skill-item">
              <i class="fa-brands fa-react" style="color:#63D8FA"></i>
              <span>React</span>
            </div>
          </div>
          <div class="col-2">
            <div class="skill-item">
              <i class="fa-brands fa-sass" style="color:#CD679A"></i>
              <span>SASS</span>
            </div>
          </div>
          <div class="col-2">
            <div class="skill-item">
              <i class="fa-brands fa-bootstrap" style="color:#26103A"></i>
              <span>Bootstrap</span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="class-content">
        <h4>Back-End</h4>
        <hr>
        <div class="row text-center">
          <div class="col-2">
            <div class="skill-item">
              <%= image_tag "ruby.png", :class => "skill-icon" %>
              <span>Ruby</span>
            </div>
          </div>
          <div class="col-2">
            <div class="skill-item">
              <%= image_tag "rails.png", :class => "skill-icon" %>
              <span>Rails</span>
            </div>
          </div>
          <div class="col-2">
            <div class="skill-item">
              <%= image_tag "postgresql.png", :class => "skill-icon" %>
              <span>PostgreSQL</span>
            </div>
          </div>
          <div class="col-2">
            <div class="skill-item">
              <%= image_tag "api.png", :class => "skill-icon" %>
              <span>RESTful APIs</span>
            </div>
          </div>
          <div class="col-2">
            <div class="skill-item">
              <%= image_tag "heroku.png", :class => "skill-icon"%>
              <span>Heroku</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_sidebar.html.erb
<div class="sidebar-wrapper">
  <nav class="sidebar hide-on-small-only">
    <ul>
      <li class="nav-item nav-about"><a href="#about"><i class='fas fa-user'></i> About</a></li>
      <li class="nav-item nav-projects"><a href="#projects"><i class='fas fa-file-code'></i> Projects</a></li>
      <li class="nav-item nav-skills"><a href="#skills"><i class='fas fa-laptop-code'></i> Skills</a></li>
      <li class="nav-item nav-education"><a href="#education"><i class='fas fa-graduation-cap'></i> Education</a></li>
      <li class="nav-item nav-contact"><a href="#contact"><i class='fas fa-envelope'></i> Contact</a></li>
      <li class="nav-item nav-blog"><a href="#blog"><i class='fas fa-blog'></i> Blog</a></li>
    </ul>
    <button class="sidebar-toggle show-on-small-only"><i class="fa-solid fa-bars"></i></button>
  </nav>
</div>